### ISSUE TITLE
When the network is disconnected, how do I take out the cached data using the CachePlugin?

### ISSUE THREAD

**Issue by ETmanwenhan** [diegotrevisan/BaseRest#1]
When the network is disconnected, how do I take out the cached data using the CachePlugin?

```swift
 let provider = MoyaProvider<T>(plugins: [NetworkLoggerPlugin(verbose: true), CachePlugin()])
```

**Comment by diegotrevisan** [comment]
In my tests, it looks like either Moya or URLRequest itself handles cached responses when out of connection. Anyway, in case it doesn't work I've added some logic to CachePlugin. Please check it out in the [cache-support](https://github.com/diegotrevisan/BaseRest/tree/cache-support) branch.

**Comment by ETmanwenhan** [comment]
I refer to the CachePlugin, why error. Response? Request = nil?

![Uploading 91906C4B-8E16-4F11-ADAB-810D624F3B8A.png…]()

**Comment by diegotrevisan** [comment]
I'm not sure I got your question but since `error.response` is an optional I need to check it exists before fetching local cache.

**Comment by ETmanwenhan** [comment]
You're on the right track. I can only issue to Moya, thank you！
